#这是一个请求的swagger_yml信息缩略
swagger: '2.0'
info:
    version: 1.0.0
    title: outer_balancethreshold
#开发测试生产环境的host不同
host: 'locahost:8080'
#basePath固定
basePath: /
#服务总述
tags:
- name: outer-controller
  description: 自动缴费托收服务
consumes:
- application/json
produces:
- application/json
paths:
    /outer/balancethreshold:
        delete:
            tags: outer-controller
            summary: 以签约用户解约
            description: "<p>未签约用户不能解约</p>\n"
            operationId: to_fill_in
            consumes:
            - application/json
            produces:
            - application/json
            parameters:
            - in: body
              name: sreq
              description: to_fill_in
              required: true
              schema:
                  $ref: '#/definitions/ServiceRequest'
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/ServiceResponse'
                '201':
                    description: to_fill_in
                '400':
                    description: 输入的参数无效
                '401':
                    description: Unauthorized
                '403':
                    description: Forbidden
                '404':
                    description: 找不到结果数据
#请求、返回的类型定义
definitions:
    ServiceResponse:
        type: object
        required:
        - MSG
        - RSP
        - STATUS
        - TXID
        properties:
            MSG:
                type: string
                example: 服务调用成功！
                description: 服务请求结果描述
            RSP:
                type: object
                required:
                - RSP_CODE
                - RSP_DESC
                properties:
                    RSP_CODE:
                        type: string
                        example: '00000'
                        description: 业务返回编码
                    RSP_DESC:
                        type: string
                        example: 数据处理正确！
                        description: 业务返回描述
                $$ref: '#/definitions/Rsp2'
            STATUS:
                type: string
                example: '0000'
                description: 服务请求结果编码
            TXID:
                type: string
                example: b393548b3dc5^1504165518997^70
                description: 服务流水号(自动生成)
    ServiceRequest:
        type: object
        required:
        - SERIAL_NUMBER
        properties:
            SERIAL_NUMBER:
                type: string
                example: '18610101010'
                description: 业务号码
