#这是一个请求的swagger_yml信息缩略
swagger: '2.0'
info:
    version: 1.0.0
    title: accounting_mdatacdr_1_{provinceId}_{eparchyId}
#开发测试生产环境的host不同
host: 'locahost:8080'
#basePath固定
basePath: /
#consumes:
#  - application/json
#produces:
#  - application/json
tags:
- name: mdatacdr
  description: 移网-数据业务详单查询微服务(mdatacdr)
paths:
    /accounting/mdatacdr_1/{provinceId}/{eparchyId}:
        get:
            tags:
#        必须字段
            - accounting-mdatacdr_1-{provinceId}-{eparchyId}-controller
            summary: 数据业务详单查询微服务_yapi写入
            description: "<p>数据业务详单查询微服务</p>\n"
            parameters:
            - name: QUERY_TYPE
              in: query
              description: 查询类型
              required: true
              type: string
              example: '11'
            - name: SERIAL_NUMBER
              in: query
              description: 业务号码
              required: true
              type: string
              example: ''
            - name: SERVICE_CLASS_CODE
              in: query
              description: 网别
              required: true
              type: string
              example: ''
            - name: USER_ID
              in: query
              description: 用户编码
              required: true
              type: string
              example: ''
            - name: START_DATE
              in: query
              description: 开始时间
              required: true
              type: string
              example: ''
            - name: provinceId
              in: path
              description: 查询省份
              required: true
              type: string
              example: true
            - name: eparchyId
              in: path
              description: 查询地市
              required: true
              type: string
              example: true
            - name: CBSS-MS-GRAY
              in: header
              description: CBSS-MS-GRAY
              required: true
              type: string
              example: true
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/ServiceResponse'
                '201':
                    description: to_fill_in
                '400':
                    description: 输入的参数无效
                '401':
                    description: Unauthorized
                '403':
                    description: Forbidden
                '404':
                    description: 找不到结果数据
#请求、返回的类型定义
definitions:
    ServiceResponse:
        type: object
        title: empty object
        properties:
            MSG:
                type: string
                description: 服务请求结果描述
                enum:
                - 服务调用成功！
                example: 服务调用成功！
            RSP:
                type: object
                properties:
                    DATA:
                        type: array
                        items:
                            type: object
                            properties:
                                RSP_CODE:
                                    type: string
                                    description: 业务返回编码
                                    enum:
                                    - '0000'
                                    example: '0000'
                                RSP_DESC:
                                    type: string
                                    description: 业务返回描述
                                    enum:
                                    - 成功
                                    example: 成功
                            required: []
                required:
                - DATA
            STATUS:
                type: string
                description: 服务请求结果编码
            TXID:
                type: string
                description: 服务流水号(自动生成)
                enum:
                - b393548b3dc5^1504165518997^70
                example: b393548b3dc5^1504165518997^70
        required:
        - MSG
        - RSP
        - STATUS
        - TXID
