#这是一个post请求的swagger_yml信息缩略
swagger: '2.0'
info:
    version: 1.0.0
    title: sd_cancelblackuser_updateCbssBlackListbyMsisdn_1
#开发测试生产环境的host不同
host: 'locahost:8080'
#basePath固定
basePath: /
consumes:
- application/x-www-form-urlencoded
produces:
- application/json
paths:
    /sd/cancelblackuser/updateCbssBlackListbyMsisdn_1:
        post:
            tags:
#        必须字段
            - sd-cancelblackuser-updateCbssBlackListbyMsisdn_1-controller
            summary: 更新用户黑名单按照手机号_yapi导入
            description: "<pre><code>根据用户手机号更新用户黑名单信息\n\n</code></pre>\n"
            operationId: to_fill_in
            consumes:
            - application/json
            produces:
            - application/json
            parameters:
            - name: msisdn
              in: formData
              description: 用户手机号整数msisdn=XXXx
              required: true
              type: string
              example: ''
            responses:
                '200':
                    description: OK
                    schema:
                        $ref: '#/definitions/ServiceResponse'
                '201':
                    description: to_fill_in
                '400':
                    description: 输入的参数无效
                '401':
                    description: Unauthorized
                '403':
                    description: Forbidden
                '404':
                    description: 找不到结果数据
#请求、返回的类型定义
definitions:
    ServiceResponse:
        type: string
        enum:
        - '"STATUS":2000,"MSG":服务降级,"TXID":8c1f^1537261122096^560781,"RSP":{"RSP_CODE":2,"RSP_DESC":getCbssUser,"DATA":[{"resultinfo":"手机号=18612819106，没有用户信息"}],"ATTACH":{}}'
        example: '"STATUS":2000,"MSG":服务降级,"TXID":8c1f^1537261122096^560781,"RSP":{"RSP_CODE":2,"RSP_DESC":getCbssUser,"DATA":[{"resultinfo":"手机号=18612819106，没有用户信息"}],"ATTACH":{}}'
